use HR_DB;

SELECT * FROM HR;

-- OVERALL ATTRITION
SELECT COUNT(CASE WHEN ATTRITION = '1' THEN 1 END) AS ATTRITION_COUNT, COUNT(*) AS TOTAL_EMPLOYEES
FROM HR;

-- PRESENCE OF OVERTIME AND ATTRITION CORRELATION
SELECT Over_Time, COUNT(*) AS TOTAL_EMPLOYEES
FROM HR
WHERE ATTRITION = 1
GROUP BY Over_Time;

-- OVERALL GENDER DISTRIBUTION IN THE DATASET
SELECT GENDER, COUNT(*) AS TOTAL_EMPLOYEES FROM HR
GROUP BY GENDER;

SELECT GENDER, COUNT(*) AS TOTAL_EMPLOYEES
FROM HR
WHERE Attrition = 1
GROUP BY GENDER;

-- RELATION BETWEEN PERFORMANCE RATING AND ATTRITION
SELECT Performance_Rating, COUNT(CASE WHEN ATTRITION = '1' THEN 1 END) AS ATTRITION_COUNT
FROM HR
GROUP BY Performance_Rating;
-- ***THERE IS A NEGATIVE CORRELATION BETWEEN THE PERFORMACE RATING AND ATTRITION COUNT

-- RELATION BETWEEN THE PERCENT SALARY HIKE AND ATTRITION COUNT
SELECT Percent_Salary_Hike, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE ATTRITION = 1
GROUP BY  Percent_Salary_Hike
ORDER BY ATTRITION_COUNT DESC;
-- ***THERE IS A NEGATIVE CORRELATION BETWEEN THE PERCENT SALARY HIKE AND ATTRITION COUNT

SELECT * FROM HR;

-- RELATION BETWEEM YEARS IN CURRENT ROLE AND ATTRITION COUNT
SELECT Years_In_Current_Role, COUNT(CASE WHEN ATTRITION = '1' THEN 1 END) AS ATTRITION_COUNT
FROM HR
WHERE Years_In_Current_Role > (SELECT AVG(Years_In_Current_Role) FROM HR)
GROUP BY Years_In_Current_Role
ORDER BY Years_In_Current_Role;
-- ***EMPLOYEES WHO ARE WORKING IN THE COMPANY FROM LAST 5-10 YEARS ARE HAVING THE HIGHEST ATTRITION COUNT

-- EMPLOYEE ATTRITION BASED ON THE AGE RANGE
SELECT CASE WHEN AGE <= 29 THEN '18-29'
            WHEN AGE >= 30 AND AGE <= 39 THEN '30-39'
			WHEN AGE >= 40 AND AGE <= 49 THEN '40-49'
			WHEN AGE >= 50 AND AGE <= 59 THEN '50-59'
			ELSE '60 OR OLDER'
			END AS 'AGE RANGE', COUNT(*) AS 'NUMBER OF ATTRITION COUNT BASED ON AGE RANGE'
FROM HR
WHERE ATTRITION = 1 AND Years_At_Company >= 2
GROUP BY CASE WHEN AGE <= 29 THEN '18-29'
            WHEN AGE >= 30 AND AGE <= 39 THEN '30-39'
			WHEN AGE >= 40 AND AGE <= 49 THEN '40-49'
			WHEN AGE >= 50 AND AGE <= 59 THEN '50-59'
			ELSE '60 OR OLDER'
			END
ORDER BY [AGE RANGE];
-- ***AGE GROUP OF '18-29' AND '30-39' HAVE THE MAXIMUM ATTRITION COUNTS FOR THOSE EMPLOYEES WHO HAVE BEEN WORKING IN THE COMPANY FROM LAST 1 

SELECT * FROM HR;

SELECT DISTINCT DEPARTMENT FROM HR;

-- DEPARTMENT WISE ATTRITION COUNT
SELECT DEPARTMENT, COUNT(*) AS ATTRITION_COUNT
FROM HR
WHERE Attrition = 1
GROUP BY Department
ORDER BY ATTRITION_COUNT DESC;
--*** R&D AND SALES DEPARTMENT ARE HAVING THE MAX ATTRITION WITH ALMOST 95%

-- ENVIRONMENT SATISFACTION, JOB SATISFACTION AND RELATIONSHIP SATISFACTION ON ATTRITION COUNTS
SELECT Environment_Satisfaction, COUNT(*) AS ATTRITION_COUNTS
FROM HR
WHERE ATTRITION = 1
GROUP BY Environment_Satisfaction
ORDER BY ATTRITION_COUNTS DESC;
-- THERE IS NO CORRELATION BETWEEN THE ENVIRONMENT SATISFACTION AND ATTRITION COUNTS

SELECT Job_Satisfaction, COUNT(*) AS ATTRITION_COUNTS
FROM HR
WHERE ATTRITION = 1
GROUP BY Job_Satisfaction
ORDER BY ATTRITION_COUNTS DESC;
-- THERE IS NO CORRELATION BETWEEN THE JOB SATISFACTION AND ATTRITION COUNTS


SELECT Relationship_Satisfaction, COUNT(*) AS ATTRITION_COUNTS
FROM HR
WHERE ATTRITION = 1
GROUP BY Relationship_Satisfaction
ORDER BY ATTRITION_COUNTS DESC;
-- THERE IS NO CORRELATION BETWEEN THE RELATIONSIP SATISFACTION AND ATTRITION COUNTS

-- WORK LIFE BALANCE AND ATTRITION COUNTS
SELECT Work_Life_Balance, COUNT(*) AS ATTRITION_COUNTS
FROM HR
WHERE Attrition = 1
GROUP BY Work_Life_Balance
ORDER BY ATTRITION_COUNTS DESC;
-- THERE IS NO RELATION BETWEEN THE WORK LIFE BALANCE AND ATTRITION COUNTS

-- DISTANCE FROM HOME AND ATTRITION COUNTS
select Distance_From_Home, count(*) as attr_count
from HR
where attrition = 1
group by Distance_From_Home
order by Distance_From_Home desc, attr_count desc;
-- THERE IS NO RELATION BETWEEN DISTANCE FROM HOME AND ATTRITION COUNTS


